(require 'module-custom)
;; (setq wen-module-lsp-frame "lsp-bridge")
(setq wen-module-obsidian-repo "~/Documents/Vaults/Work/")

;; (require 'module-org-roam)
(require 'module-obsidian)
(require 'module-git)
(require 'module-gtags)
(require 'module-company)
(require 'module-c)
;; (require 'module-graphviz)
(require 'module-plantuml)
(require 'module-d2)
(require 'module-mermaid)
(require 'module-webdev)
(require 'module-hugo)
(require 'module-chatgpt)
